package com.gameon.model.enums;

public enum NotificationType {
    FOLLOW_NEW,
    JOIN_REQUEST_RECEIVED,
    JOIN_ACCEPTED,
    JOIN_REJECTED,
    JOIN_WITHDRAWN,
    LISTING_CONFIRMED,
    LISTING_CANCELLED_INSUFFICIENT_PLAYERS,
    MATCH_RESULT_POSTED,
    MATCH_RESULT_UPDATED,
    LISTING_CANCELLED,
    LISTING_INVITE
}
